Repository eunomia-bpf/llvmbpf, pull requests merged in 2024-08, with the labels that each got.

#1 CI: fix vm test and add llvm ir generate
  .github/workflows/test-vm.yml
  .github/workflows/unit-test.yml
  .gitignore
  CMakeLists.txt
  README.md
  cli/main.cpp
  src/llvm_jit_context.cpp
  test/CMakeLists.txt
  test/bpf_conformance_runner/CMakeLists.txt
  test/bpf_conformance_runner/main-bpf-conformance.cpp
  test/unit-test/CMakeLists.txt
  test/unit-test/bpf_progs.h
  test/unit-test/llvm-aot.cpp
Labels: size/L

#4 rename the library name for bpftime
  .github/workflows/bpf_conformance.yml
  .gitignore
  CMakeLists.txt
  README.md
  cli/CMakeLists.txt
  cli/main.cpp
  example/CMakeLists.txt
  example/main.cpp
  include/llvmbpf.hpp
  src/llvm_jit_context.cpp
  src/llvm_jit_context.hpp
  src/vm.cpp
  test/bpf_conformance_runner/CMakeLists.txt
  test/bpf_conformance_runner/main-bpf-conformance.cpp
  test/unit-test/CMakeLists.txt
  test/unit-test/llvm-aot.cpp
Labels: size/M

#7 fix: build dependency issue
  .github/workflows/bpf_conformance.yml
  .github/workflows/test-aot-cli.yml
  .github/workflows/test-vm.yml
  .github/workflows/unit-test.yml
  CMakeLists.txt
  cli/CMakeLists.txt
  test/unit-test/CMakeLists.txt
Labels: size/L

#8 fix: Add extra check for Catch2 target definition
  CMakeLists.txt
  test/unit-test/CMakeLists.txt
Labels: size/XS

#5 Create codeql.yml
  .github/workflows/codeql.yml
Labels: size/M

#9 feat: use ubpf insn defines
  .gitignore
  CMakeLists.txt
  README.md
  src/compiler.cpp
  src/compiler_utils.cpp
  src/compiler_utils.hpp
  src/ebpf_inst.h
  test/unit-test/CMakeLists.txt
  test/unit-test/bpf_prog_test.cpp
Labels: size/L

#12 ci: use codecov
  .github/assets/bpf_conformance_test.txt
  .github/workflows/bpf_conformance.yml
  .github/workflows/test-aot-cli.yml
  .github/workflows/test-vm.yml
  .github/workflows/unit-test.yml
  README.md
  codecov.yaml
Labels: size/XL

#13 fix: refactor error handling
  .github/workflows/test-aot-cli.yml
  README.md
  cli/README.md
  cli/main.cpp
  example/CMakeLists.txt
  example/basic.cpp
  include/llvmbpf.hpp
  src/llvm_jit_context.cpp
  src/llvm_jit_context.hpp
  src/vm.cpp
  test/unit-test/CMakeLists.txt
  test/unit-test/bpf_prog_test.cpp
  test/unit-test/bpf_progs.h
  test/unit-test/vm_test.cpp
Labels: size/L

#14 add map examples
  .github/workflows/unit-test.yml
  codecov.yaml
  example/CMakeLists.txt
  example/basic.cpp
  example/maps.cpp
  src/compiler.cpp
  src/llvm_jit_context.cpp
  src/llvm_jit_context.hpp
  src/vm.cpp
  test/unit-test/vm_test.cpp
Labels: size/L

#15 docs: add more example and usage
  .gitignore
  README.md
  cli/main.cpp
  example/inline/Makefile
  example/inline/libmap.c
  example/inline/libmap.ll
  example/inline/main.c
  example/inline/xdp-counter.ll
  example/load-llvm-ir/Makefile
  example/load-llvm-ir/bpf_module.c
  example/standalone/Makefile
  example/standalone/main.c
  example/standalone/xdp-counter.ll
  example/xdp-counter.json
Labels: size/XXL
